spring.application.name=urlencurtador

spring.data.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=URL_Encurtador
spring.data.mongodb.username=admin
spring.data.mongodb.password=123